<!DOCTYPE html> 
<html>
 <head>
                <link href="css/main.css" type="text/css" rel="stylesheet" />
				<link href="css/bootstrap.css" type="text/css" rel="stylesheet" />
                <link href="css/sttolkit.css" type="text/css" rel="stylesheet" />
                <link href="css/layerslider.css" type="text/css" rel="stylesheet" />
                <link href="css/contact-form.css" type="text/css" rel="stylesheet" />
                <script src="js/shortcode.min.js" type="text/javascript" ></script>
                <script src="js/underscore.min.js" type="text/javascript" ></script>
                <script src="js/wp-emoji-release.min" type="text/javascript" ></script>
</head>
<body>
 <div class="form-group pull-right nepokretnosti-buttons">
                                    <input type="submit" id="submit" name="send" class="btn btn-default" value="Posalji Email">
                                    <input type="button" class="btn btn-default" onclick="resetuj()" value="Resetuj">
  </div>
 </body>
 </html>